INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-18, 'Menu Outros Vinculos', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-17, 'Menu Contratos', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-16, 'Menu Repasse', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-15, 'Menu Municipio', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-14, 'Menu Programa', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-13, 'Menu Conta Bancaria', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-12, 'Menu Usuario', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-11, 'Menu Tipo de Unidade Medida', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-10, 'Menu Tipo de Vinculo', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-9, 'Menu Tipo de Valor', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-8, 'Menu Tipo de Fomalização', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-7, 'Menu Tipo de Evento', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-6, 'Menu Secretaria', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-5, 'Menu Porte Municipal', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-4, 'Menu Perfil', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-3, 'Menu Grupo Repasse', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-2, 'Menu Funcionalidade', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(-1, 'Menu Banco', 'menu', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(1, 'CadastroDeFucionalidade', 'Teste', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(7, 'Consulta usuário por CPF', 'usuario', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(8, 'Listar funcionalidades', 'funcionalidade', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(9, 'Confirmar Token', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(10, 'Cadastrar Banco', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(11, 'Alterar Banco', 'banco', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(12, 'Deletar Banco', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(13, 'Ativar Banco', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(14, 'Listar Todos os Bancos', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(15, 'Cadastrar Conta', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(16, 'Alterar Conta', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(17, 'Deletar Conta', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(18, 'Ativar Conta', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(19, 'Listar Todas as Contas', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(20, 'Cadastrar Contrato', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(21, 'Alterar Contrato', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(22, 'Deletar Contrato', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(23, 'Ativar Contrato', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(24, 'Listar Todos os Contratos', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(25, 'Pesquisa Avançada de Contratos', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(26, 'Cadastrar Funcionalidade', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(27, 'Alterar Funcionalidade', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(29, 'Deletar Funcionalidade', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(30, 'Ativar Funcionalidade ', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(31, 'Listar todas as Funcionalidades', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(32, 'Cadastrar Grupo Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(33, 'Alterar Grupo Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(34, 'Deletar Grupo Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(35, 'Ativar Grupo Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(36, 'Listar Todos Grupos Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(37, 'Cadastrar Item', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(38, 'Alterar Item', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(39, 'Listar Todos os Itens', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(40, 'Listar Por Tipo de Item', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(41, 'Cadastrar Login', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(42, 'Cadastrar Lote', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(43, 'Alterar Lote', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(44, 'Deletar Lote', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(45, 'Listar Lote Por Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(46, 'Cadastrar Municipio', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(47, 'Alterar Municipio', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(48, 'Consultar Municipio Por UF', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(49, 'Bloquear Municipio', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(50, 'Listar Todos os Municipios', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(51, 'Cadastrar Municipio Habitantes', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(52, 'Alterar Municipio Habitantes', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(53, 'Deletar Municipio Habitantes', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(54, 'Cadastrar Municipio Programa Conta', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(55, 'Deletar Municipio Programa Conta', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(56, 'Cadastrar Parcelamento Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(57, 'Cadastrar Parcelamento', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(58, 'Alterar Parcelamento Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(59, 'Bloqueio Parcelamento Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(60, 'Cadastrar Perfil', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(61, 'Alterar Perfil', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(62, 'Deletar Perfil', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(63, 'Listar Todos os Perfis', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(64, 'Cadastrar Porte Municipal', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(65, 'Alterar Porte Municipal', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(66, 'Deletar Porte Municipal', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(67, 'Ativar Porte Municipal', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(68, 'Listar Todos Portes Municipais', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(69, 'Cadastrar Programa', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(70, 'Alterar Programa', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(71, 'Deletar Programa', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(72, 'Ativar Programa', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(73, 'Listar Todos os Programas', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(75, 'Alterar Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(76, 'Deletar Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(77, 'Ativar Repasse', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(78, 'Listar Todos os Repasses', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(79, 'Pesquisa Avançada de Repasses', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(80, 'Cadastrar Secretaria', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(81, 'Alterar Secretaria', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(82, 'Deletar Secretaria', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(83, 'Ativar Secretaria', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(84, 'Listar Todas as Secretarias', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(85, 'Listar Secretarias Por Status', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(86, 'Cadastrar Tipo Evento', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(87, 'Alterar Tipo Evento', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(88, 'Deletar Tipo Evento', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(89, 'Ativar Tipo Evento', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(90, 'Listar Todos Tipo Evento', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(91, 'Listar Tipo Evento Por Status', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(92, 'Cadastrar Tipo Formalizacao', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(93, 'Alterar Tipo Formalizacao', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(94, 'Deletar Tipo Formalizacao', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(95, 'Ativar Tipo Formalizacao', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(96, 'Listar Todos os Tipos de Formalizacao', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(97, 'Listar Tipo Formalizacao Por Status', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(98, 'Cadastrar Tipo Valor', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(99, 'Alterar Tipo Valor', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(100, 'Deletar Tipo Valor', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(101, 'Ativar Tipo Valor', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(102, 'Listar Todos Tipo Valor', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(103, 'Cadastrar Tipo Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(104, 'Alterar Tipo Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(105, 'Deletar Tipo Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(106, 'Ativar Tipo Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(107, 'Listar Todos Tipo Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(108, 'Listar Tipo Vinculo Por Status', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(109, 'Cadastrar Unidade Medida', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(110, 'Alterar Unidade Medida', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(111, 'Deletar Unidade Medida', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(112, 'Ativar Unidade Medida', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(113, 'Listar Todos Unidade Medida', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(114, 'Listar Unidade Medida Por Status', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(115, 'Cadastrar Usuario', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(116, 'Consultar Paginado Usuario', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(117, 'Alterar Usuario', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(118, 'Deletar Usuario', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(119, 'Ativar Usuario', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(120, 'Listar Todos Usuario', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(121, 'Cadastrar Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(122, 'Alterar Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(123, 'Deletar Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(124, 'Ativar Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(125, 'Consultar Vinculo Por Tipo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(126, 'Listar Todos Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(127, 'Pesquisa Avançada Vinculo', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(248, 'Ativar Perfil', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(249, 'Portal de serviço', 'Admin', 'S');
INSERT INTO pacto.funcionalidade (id, nome, grupo, status) VALUES(291, 'Cadastrar Repasse', 'Admin', 'S');
